version: "3"
services:
  python:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        - USERNAME=${USERNAME}
    container_name: "${PROJECT_NAME}_python"
    environment:
      - TZ=Asia/Tokyo
      - SELENIUM_GRID_HOST=${PROJECT_NAME}_chrome
    tty: true
    user: "${USERNAME}:${USERNAME}"
    volumes:
      - ${LOCAL_HOST_PATH}:/${PROJECT_NAME}
    working_dir: "/${PROJECT_NAME}"
  chrome:
      image: selenium/standalone-chrome:4.0.0-rc-1-prerelease-20210713
      container_name: "${PROJECT_NAME}_chrome"
      shm_size: 2gb
      ports:
        - "4444:4444"
        - "7900:7900"
